FROM node:20-alpine3.16

ARG HOSTNAME
ARG DB_TYPE
ARG DB_HOST
ARG POSTGRES_PORT
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB
ARG PORT
ARG SHARED_DIR_FULL_PATH
ARG FT_UID
ARG FT_SECRET_UID
ARG SECRET

ENV HOSTNAME=${HOSTNAME}
ENV DB_TYPE=${DB_TYPE}
ENV DB_HOST=${DB_HOST}
ENV POSTGRES_PORT=${POSTGRES_PORT}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_DB=${POSTGRES_DB}
ENV PORT=${PORT}
ENV SHARED_DIR_FULL_PATH=${SHARED_DIR_FULL_PATH}
ENV FT_UID=${FT_UID}
ENV FT_SECRET_UID=${FT_SECRET_UID}
ENV SECRET=${SECRET}


RUN mkdir -p /var/app/

WORKDIR /var/app

COPY ./nestjs /var/app

RUN npm i
RUN npm run build

CMD ["npm", "run", "start:prod"]
# CMD ["sleep", "infinity"]